[tools]
coursier = "latest"
go = "latest"
java = "temurin-21"
node = "lts"
python = "3.14"
ruff = "latest"
ty = "latest"
uv = "latest"
zig = "0.15.2"
zls = "0.15.1"

"npm:typescript-language-server" = "latest"
"npm:prettier" = "latest"
